apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-svc
  namespace: sample-app-2
  labels:
    app: gateway-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-svc
  template:
    metadata:
      labels:
        app: gateway-svc
    spec:
      containers:
      - name: gateway-svc
        image: "sample-2-gateway-svc:latest"
        imagePullPolicy: Never
        ports:
          - containerPort: 3100
        envFrom:
        - configMapRef:
            name: sample-app-2-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
  namespace: sample-app-2
spec:
  type: NodePort
  selector:
    app: gateway-svc
  ports:
  - protocol: TCP
    port: 3100
    targetPort: 3100
    nodePort: 31100
